#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2020, ROE (http://www.roe.ac.uk/)
#
#     This information is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This information is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#   </meta:licence>
# </meta:header>
#
#

all:

    vars:

    # Hadoop vars

        hdname: "hadoop-3.1.3"
        hdbase: "/opt"
        hdhome: "/opt/hadoop"

        hdconf: "{{hdhome}}/etc/hadoop"
        hdhost: "master01"
        hduser: "fedora"

    # HDFS vars

        hdfsconf: "/var/hdfs/conf"
        hdfsuser: "fedora"

  # Spark vars
        spname: "spark-2.4.7"
        spfull: "spark-2.4.7-bin-hadoop2.7"
        spbase: "/opt"
        sphome: "/opt/spark"
        sphost: "master01"
        spuser: "fedora"

        sparkconfig: |

            # https://spark.apache.org/docs/latest/configuration.html
            # https://spark.apache.org/docs/latest/running-on-yarn.html
            # https://stackoverflow.com/questions/37871194/how-to-tune-spark-executor-number-cores-and-executor-memory

            spark.master                 yarn

            # Amount of memory to use for the driver process (where SparkContext is initialized).
            # (small zeppelin node has 22G memory)
            #spark.driver.memory          10g
            spark.driver.memory           12g
            # Limit of total size of serialized results of all partitions for each Spark action.
            # Setting a proper limit can protect the driver from out-of-memory errors.
            spark.driver.maxResultSize     8g

            # Amount of memory to use for the YARN Application Master
            # (default 512m)
            spark.yarn.am.memory        512m

            # Number of cores to use for the YARN Application Master in client mode.
            # (default 1)
            #spark.yarn.am.cores            1

            # The number of cores to use on each executor.
            # (medium worker node has 14 cores)
            #spark.executor.cores           7
            spark.executor.cores            4
            # Amount of memory to use per executor process.
            # (medium worker node has 45G memorys)
            # (45G - 512M)/2
            # ((45 * 1024)-512)/2
            #spark.executor.memory     22784m
            spark.executor.memory         12g

            # The number of executors for static allocation.
            # 4w * 2
            #spark.executor.instances       8
            spark.executor.instances       11

        yarnconfig: |
            <!--+
                | Maximum limit of memory to allocate to each container request at the Resource Manager.
                | https://stackoverflow.com/a/43827548
                | https://github.com/hortonworks/hdp-configuration-utils
                +-->
            <property>
                <name>yarn.scheduler.maximum-allocation-mb</name>
                <value>14000</value>
            </property>

            <!--+
                | Minimum limit of memory to allocate to each container request at the Resource Manager.
                | https://stackoverflow.com/a/43827548
                | https://github.com/hortonworks/hdp-configuration-utils
                +-->
            <property>
                <name>yarn.scheduler.minimum-allocation-mb</name>
                <value>11000</value>
            </property>


    # Zeppelin vars
        zepname: "zeppelin-0.8.2"
        zepbase: "/home/fedora"
        zephome: "/home/fedora/zeppelin-0.8.2-bin-all"
        zephost: "zeppelin"
        zepuser: "fedora"

    hosts:

        zeppelin:
            login:  'fedora'
            image:  'Fedora-30-1.2'
            flavor: 'gaia.cclake.6vcpu'
            discs:
              - type: 'cinder'
                size: 512
                format: 'btrfs'
                mntpath: "/mnt/cinder/vdb"
                devname: 'vdb'
            paths:
                # Empty on Zeppelin, master, worker
                hddatalink: "/var/hadoop/data"
                hddatadest: "/mnt/local/vda/hadoop/data"
                # Empty on Zeppelin
                hdtemplink: "/var/hadoop/temp"
                hdtempdest: "/mnt/local/vda/hadoop/temp"
                # Empty on Zeppelin
                hdlogslink: "/var/hadoop/logs"
                hdlogsdest: "/mnt/local/vda/hadoop/logs"
                # Used on Zeppelin
                sptemplink: "/var/spark/temp"
                sptempdest: "/mnt/cinder/vdb/spark/temp"

        monitor:
            login:  'fedora'
            image:  'Fedora-30-1.2'
            flavor: 'gaia.cclake.2vcpu'
            discs: []

    children:

        masters:
            hosts:
                master[01:01]:
            vars:
                login:  'fedora'
                image:  'Fedora-30-1.2'
                flavor: 'gaia.cclake.2vcpu'
                discs: []
                paths:
                    # Empty on Zeppelin, master, worker
                    hddatalink: "/var/hadoop/data"
                    hddatadest: "/mnt/local/vda/hadoop/data"
                    # Used on master
                    # /var/hadoop/temp/dfs/namesecondary/current/
                    hdtemplink: "/var/hadoop/temp"
                    hdtempdest: "/mnt/local/vda/hadoop/temp"
                    # Used on master
                    hdlogslink: "/var/hadoop/logs"
                    hdlogsdest: "/mnt/local/vda/hadoop/logs"
                    # Used on master
                    # /var/hdfs/meta/namenode/fsimage/current/
                    hdfsmetalink: "/var/hdfs/meta"
                    hdfsmetadest: "/mnt/local/vda/hadoop/meta"

        workers:
            hosts:
                worker[01:04]:
            vars:
                login:  'fedora'
                image:  'Fedora-30-1.2'
                flavor: 'gaia.cclake.13vcpu'
                discs:
                  - type: 'local'
                    format: 'ext4'
                    mntpath: "/mnt/local/vdb"
                    devname: 'vdb'
                  - type: 'cinder'
                    size: 1024
                    format: 'btrfs'
                    mntpath: "/mnt/cinder/vdc"
                    devname: 'vdc'
                paths:
                    # Empty on Zeppelin, master, worker
                    hddatalink: "/var/hadoop/data"
                    hddatadest: "/mnt/local/vda/hadoop/data"
                    # Used on workers
                    # /var/hadoop/temp/nm-local-dir/
                    hdtemplink: "/var/hadoop/temp"
                    hdtempdest: "/mnt/local/vdb/hadoop/temp"
                    # Used on worker
                    hdlogslink: "/var/hadoop/logs"
                    hdlogsdest: "/mnt/local/vda/hadoop/logs"
                    # Workers only, empty
                    hdfslogslink: "/var/hdfs/logs"
                    hdfslogsdest: "/mnt/local/vda/hdfs/logs"
                    # Workers only, used
                    hdfsdatalink: "/var/hdfs/data"
                    hdfsdatadest: "/mnt/cinder/vdc/hdfs/data"

