#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2020, ROE (http://www.roe.ac.uk/)
#
#     This information is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This information is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#   </meta:licence>
# </meta:header>
#
#

- name: "Configure MapReduce masters"
  hosts: masters
  gather_facts: false
  vars:
    hdname: "hadoop-3.2.1"
    hdbase: "/opt"
    hdhome: "/opt/hadoop"
    hddata: "/var/local/hadoop"
    hdhost: "{{groups['masters'][0]}}"
    hduser: "{{hostvars[inventory_hostname].login}}"

  tasks:

    #
    # Comments from mapred-default.xml
    # [fedora@master01] vi /opt/hadoop/share/doc/hadoop/hadoop-mapreduce-client/hadoop-mapreduce-client-core/mapred-default.xml
    #
    # mapred-default.xml
    # mapred.child.java.opts
    #  Usage of -Djava.library.path can cause programs to no longer function if
    #  hadoop native libraries are used. These values should instead be set as part
    #  of LD_LIBRARY_PATH in the map / reduce JVM env using the mapreduce.map.env and
    #  mapreduce.reduce.env config settings.
    #
    - name: "Configure [{{hdhome}}/etc/hadoop/mapred-site.xml]"
      become: true
      blockinfile:
        path: "{{hdhome}}/etc/hadoop/mapred-site.xml"
        marker: "<!-- {mark} Ansible managed MapReduce worker config -->"
        insertbefore: "</configuration>"
        block: |
            <!--+
                | The runtime framework for executing MapReduce jobs.
                | Can be one of local, classic or yarn.
                +-->
            <property>
                <name>mapreduce.framework.name</name>
                <value>yarn</value>
            </property>

            <!--+
                | User added environment variables for the MR App Master
                | processes, specified as a comma separated list.
                | Example:
                | 1) A=foo  This will set the env variable A to foo
                | 2) B=$B:c This is inherit tasktracker's B env variable.
                |
                | To define environment variables individually, you can specify
                | multiple properties of the form yarn.app.mapreduce.am.env.VARNAME,
                | where VARNAME is the name of the environment variable. This is the only
                | way to add a variable when its value contains commas.
                |
                | mapred-default.xml
                | -
                +-->
            <property>
                <name>yarn.app.mapreduce.am.env</name>
                <value>HADOOP_MAPRED_HOME={{hdhome}}</value>
            </property>

            <!--+
                | User added environment variables for the map task processes,
                | specified as a comma separated list.
                | Example:
                | VAR1=value1,VAR2=value2
                |
                | To define environment variables individually, you can specify
                | multiple properties of the form mapreduce.map.env.VARNAME,
                | where VARNAME is the name of the environment variable. This is the only
                | way to add a variable when its value contains commas.
                |
                | mapred-default.xml
                | "This is commented out so that it won't override mapred.child.env."
                | -
                +-->
            <property>
                <name>mapreduce.map.env</name>
                <value>HADOOP_MAPRED_HOME={{hdhome}}</value>
            </property>

            <!--+
                | User added environment variables for the reduce task processes,
                | specified as a comma separated list.
                | Example:
                | VAR1=value1,VAR2=value2
                |
                | To define environment variables individually, you can specify
                | multiple properties of the form mapreduce.reduce.env.VARNAME,
                | where VARNAME is the name of the environment variable. This is the only
                | way to add a variable when its value contains commas.
                | contains commas.
                |
                | mapred-default.xml
                | "This is commented out so that it won't override mapred.child.env."
                | -
                +-->
            <property>
                <name>mapreduce.reduce.env</name>
                <value>HADOOP_MAPRED_HOME={{hdhome}}</value>
            </property>

            <!--+
                | The amount of memory the MR AppMaster needs.
                |
                | mapred-default.xml
                | 1536
                +-->
            <property>
                <name>yarn.app.mapreduce.am.resource.mb</name>
                <value>15000</value>
            </property>

            <!--+
                | The amount of memory to request from the scheduler for each
                | map task. If this is not specified or is non-positive, it is inferred from
                | mapreduce.map.java.opts and mapreduce.job.heap.memory-mb.ratio.
                | If java-opts are also not specified, we set it to 1024.
                |
                | mapred-default.xml
                | -1
                +-->
            <property>
                <name>mapreduce.map.memory.mb</name>
                <value>7000</value>
            </property>

            <!--+
                | The amount of memory to request from the scheduler for each
                | reduce task. If this is not specified or is non-positive, it is inferred
                | from mapreduce.reduce.java.opts and mapreduce.job.heap.memory-mb.ratio.
                | If java-opts are also not specified, we set it to 1024.
                |
                | mapred-default.xml
                | -1
                +-->
            <property>
                <name>mapreduce.reduce.memory.mb</name>
                <value>7000</value>
            </property>
