#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2020, ROE (http://www.roe.ac.uk/)
#
#     This information is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This information is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#   </meta:licence>
# </meta:header>
#


- name: "Install Zeppelin"
  hosts: masters:workers:zeppelin
  become: yes
  become_user: root
  gather_facts: false
  vars_files:
    - config/ansible.yml
    - /tmp/ansible-vars.yml
  vars:
    zepbase: "/opt"
    zepipaddress: "hostvars['zeppelin']['ansible_default_ipv4']['address']"

  tasks:

    - name: "Install python-dev package"
      become: true
      yum:
        name:  'python-devel'
        state: present

    - name: "Install libevent-devel package"
      become: true
      yum:
        name:  'libevent-devel'
        state: present

    - name: "Install gcc package"
      become: true
      yum:
        name:  'gcc'
        state: present

    - name: "Install Python3-devel package"
      become: true
      yum:
        name:  'python3-devel'
        state: present

    - name: "Change Python to Python3"
      command: update-alternatives --install /usr/bin/python python /usr/bin/python3 10


    - name: "Create [/etc/profile.d/python.sh]"
      become: true
      blockinfile:
        dest:  '/etc/profile.d/python.sh'
        state: present
        owner: 'root'
        group: 'root'
        mode:  'u=rw,g=r,o=r'
        create: yes
        insertafter: 'EOF'
        marker: '# {mark} Ansible managed Python'
        block: |
          alias python=python3
