#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2020, ROE (http://www.roe.ac.uk/)
#
#     This information is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This information is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#   </meta:licence>
# </meta:header>
#


- name: "Install Python libraries"
  hosts: masters:workers:zeppelin
  gather_facts: false
  vars_files:
    - config/ansible.yml
    - /tmp/ansible-vars.yml


  tasks:

    - name: "Install required system libraries"
      become: true
      yum:
        name: libtiff-devel,libjpeg-devel,libzip-devel,freetype-devel,lcms2-devel,libwebp-devel,tcl-devel,tk-devel
        update_cache: true
        state: present

    - name: Copy pip requirements file into tmp
      become: true
      copy:
        src: "{{ playbook_dir | dirname | dirname }}/common/pip/requirements.txt"
        dest: "/tmp/requirements.txt"

    - name: Install the required Python packages
      become: true
      pip:
        requirements: "/tmp/requirements.txt"
