#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2020, ROE (http://www.roe.ac.uk/)
#
#     This information is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This information is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#   </meta:licence>
# </meta:header>
#
#

all:

    vars:

        cloudname:  "{{aglais.spec.openstack.cloud}}"
        deployname: "{{aglais.status.deployment.name}}"

        sshkeys: "{{ deployname }}-keypair"

        networks:
            internal: "{{ deployname }}-internal-network"
            external: 'internet'
            cumulus:  'cumulus-internal'

        security:
            gateway:  "{{ deployname }}-gateway-security"
            zeppelin: "{{ deployname }}-zeppelin-security"
            masters:  "{{ deployname }}-master-security"
            workers:  "{{ deployname }}-worker-security"

        ansible_ssh_common_args: "-F {{ lookup('env','HOME') }}/.ssh/ansible-config"

        # https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html
        ansible_interpreter_python: 'auto'

        # https://docs.ansible.com/ansible/latest/user_guide/intro_getting_started.html#host-key-checking
        ansible_host_key_checking: false

    # Hadoop vars

        hdname: "hadoop-3.1.3"
        hdbase: "/opt"
        hdhome: "/opt/hadoop"

        hdconf: "{{hdhome}}/etc/hadoop"
        hdhost: "master01"
        hduser: "fedora"

        hddatalink: "/var/hadoop/data"
        hddatadest: "/mnt/cinder/vdc/hadoop/data"

        hdtemplink: "/var/hadoop/temp"
        hdtempdest: "/mnt/local/vdb/hadoop/temp"

        hdlogslink: "/var/hadoop/logs"
        hdlogsdest: "/mnt/cinder/vdc/hadoop/logs"

    # HDFS vars

        hdfsconf: "/var/hdfs/conf"
        hdfsuser: "fedora"

        hdfsmetalink: "/var/hdfs/meta"
        hdfsmetadest: "/mnt/cinder/vdc/hdfs/meta"

        hdfslogslink: "/var/hdfs/logs"
        hdfslogsdest: "/mnt/cinder/vdc/hdfs/logs"

        hdfsdatalink: "/var/hdfs/data"
        hdfsdatadest: "/mnt/cinder/vdc/hdfs/data"

  # Spark vars
        spname: "spark-2.4.7"
        spfull: "spark-2.4.7-bin-hadoop2.7"
        spbase: "/opt"
        sphome: "/opt/spark"
        sphost: "master01"
        spuser: "fedora"

        sptemplink: "/var/spark/temp"
        sptempdest: "/mnt/local/vdb/spark/temp"

    # Zeppelin vars
        zepname: "zeppelin-0.8.2"
        zepbase: "/home/fedora"
        zephome: "/home/fedora/zeppelin-0.8.2-bin-all"
        zephost: "zeppelin"
        zepuser: "fedora"

        #zepdatalink: '/var/zeppelin/data'
        #zepdatadest: "/mnt/cinder/vdc/zeppelin/data"

    # User accounts and ssh keys.
        users:
            dcr:
                sshkey: 'dmr.roe.ac.uk.rsa.pub'
            dmr:
                sshkey: 'dmr.roe.ac.uk.rsa.pub'
            nch:
                sshkey: 'nch.roe.ac.uk.rsa.pub'
            stv:
                sshkey: 'stv.roe.ac.uk.rsa.pub'
            zrq:
                sshkey: 'zrq.openstack.cam.ac.uk.rsa.pub'

    hosts:

        zeppelin:
            login:  'fedora'
            image:  'Fedora-30-1.2'
            flavor: 'general.v1.medium'
            discs:
              - type: 'local'
                format: 'ext4'
                mntpath: "/mnt/local/vdb"
                devname: 'vdb'
              - type: 'cinder'
                size: 512
                format: 'btrfs'
                mntpath: "/mnt/cinder/vdb"
                devname: 'vdc'

    children:

        masters:
            hosts:
                master[01:01]:
            vars:
                login:  'fedora'
                image:  'Fedora-30-1.2'
                flavor: 'general.v1.small'

        workers:
            hosts:
                worker[01:04]:
            vars:
                login:  'fedora'
                image:  'Fedora-30-1.2'
                flavor: 'general.v1.medium'
                discs:
                  - type: 'local'
                    format: 'ext4'
                    mntpath: "/mnt/local/vdb"
                    devname: 'vdb'
                  - type: 'cinder'
                    size: 512
                    format: 'btrfs'
                    mntpath: "/mnt/cinder/vdc"
                    devname: 'vdc'

